services:
  postgres:
    image: postgres:17
    container_name: toss-trader-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: giri
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toss_trader
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: toss-dca-trader-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/toss_trader
      SPRING_DATASOURCE_USERNAME: giri
      SPRING_DATASOURCE_PASSWORD: password
      TOSS_SEC_API_KEY: ${TOSS_SEC_API_KEY}
      TOSS_SEC_SECRET_KEY: ${TOSS_SEC_SECRET_KEY}
    depends_on:
      - postgres
