services:
  postgres:
    image: postgres:17
    container_name: toss-trader-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: giri
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toss_trader
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: toss-dca-trader-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/toss_trader
      SPRING_DATASOURCE_USERNAME: giri
      SPRING_DATASOURCE_PASSWORD: password
      TOSS_SEC_API_KEY: ${TOSS_SEC_API_KEY}
      TOSS_SEC_SECRET_KEY: ${TOSS_SEC_SECRET_KEY}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-smtp.gmail.com}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-587}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      TRADER_NOTIFICATION_EMAIL: ${TRADER_NOTIFICATION_EMAIL}
    depends_on:
      - postgres
